Repository friendica/friendica-addons, pull requests merged in 2020-10, with the labels that each got.

#1026 Restructure Security classes
  statusnet/library/twitteroauth.php
  tumblr/library/tumblroauth.php
Labels: 2019.12

#1027 [langfilter] Add slider to addon settings
  langfilter/composer.json
  langfilter/composer.lock
  langfilter/lang/C/messages.po
  langfilter/langfilter.php
  langfilter/templates/settings.tpl
  langfilter/vendor/autoload.php
  langfilter/vendor/composer/ClassLoader.php
  langfilter/vendor/composer/LICENSE
  langfilter/vendor/composer/autoload_classmap.php
  langfilter/vendor/composer/autoload_namespaces.php
  langfilter/vendor/composer/autoload_psr4.php
  langfilter/vendor/composer/autoload_real.php
  langfilter/vendor/composer/autoload_static.php
  langfilter/vendor/composer/installed.json
  langfilter/vendor/matriphe/iso-639/.gitignore
  langfilter/vendor/matriphe/iso-639/.php_cs
  langfilter/vendor/matriphe/iso-639/.travis.yml
  langfilter/vendor/matriphe/iso-639/README.md
  langfilter/vendor/matriphe/iso-639/composer.json
  langfilter/vendor/matriphe/iso-639/phpunit.xml
  langfilter/vendor/matriphe/iso-639/resources/iso-639.csv.gz
  langfilter/vendor/matriphe/iso-639/resources/iso-639.sql.gz
  langfilter/vendor/matriphe/iso-639/resources/wikipedia.csv
  langfilter/vendor/matriphe/iso-639/src/ISO639.php
  langfilter/vendor/matriphe/iso-639/tests/ISO639Test.php
Labels: 2020.12

#1028 Twitter: Offer the disconnect button when the account data is invalid
  twitter/twitter.php
Labels: 2020.12, hacktoberfest-accepted

#1030 DE, IT translation updates for the langfilter
  langfilter/lang/de/messagespo.po
  langfilter/lang/de/strings.php
  langfilter/lang/it/messages.po
  langfilter/lang/it/strings.php
Labels: 2020.12

#1033 [langfilter] Remove Composer dependency
  langfilter/composer.json
  langfilter/composer.lock
  langfilter/langfilter.php
  langfilter/vendor/autoload.php
  langfilter/vendor/composer/ClassLoader.php
  langfilter/vendor/composer/LICENSE
  langfilter/vendor/composer/autoload_classmap.php
  langfilter/vendor/composer/autoload_namespaces.php
  langfilter/vendor/composer/autoload_psr4.php
  langfilter/vendor/composer/autoload_real.php
  langfilter/vendor/composer/autoload_static.php
  langfilter/vendor/composer/installed.json
  langfilter/vendor/matriphe/iso-639/.gitignore
  langfilter/vendor/matriphe/iso-639/.php_cs
  langfilter/vendor/matriphe/iso-639/.travis.yml
  langfilter/vendor/matriphe/iso-639/README.md
  langfilter/vendor/matriphe/iso-639/composer.json
  langfilter/vendor/matriphe/iso-639/phpunit.xml
  langfilter/vendor/matriphe/iso-639/resources/iso-639.csv.gz
  langfilter/vendor/matriphe/iso-639/resources/iso-639.sql.gz
  langfilter/vendor/matriphe/iso-639/resources/wikipedia.csv
  langfilter/vendor/matriphe/iso-639/src/ISO639.php
  langfilter/vendor/matriphe/iso-639/tests/ISO639Test.php
Labels: 2020.12

#1034 Twitter: Support for real reshares added
  twitter/twitter.php
Labels: 2020.12

#1035 RU translation of the langfilter and diaspora addons THX Alexander An
  diaspora/lang/ru/messages.po
  diaspora/lang/ru/strings.php
  langfilter/lang/ru/messages.po
  langfilter/lang/ru/strings.php
Labels: 2020.12

#1032 [various] Remove $binary flag for HTTPRequest
  mailstream/mailstream.php
  pumpio/pumpio.php
  statusnet/statusnet.php
  twitter/twitter.php
Labels: 2020.12

#1037 [twitter] Add new parse_link hook function
  twitter/lang/C/messages.po
  twitter/twitter.php
Labels: 2020.12

#1038 twitter addon DE translation updated
  twitter/lang/de/messages.po
  twitter/lang/de/strings.php
Labels: 2020.12
