Repository friendica/friendica-addons, pull requests merged in 2021-10, with the labels that each got.

#1175 [nitter] addon version update - reload of the addon required
  nitter/lang/C/messages.po
  nitter/nitter.php
Labels: 2021.12

#1176 [nitter] DE translation and I forgot the updated README in the other PR
  nitter/README.md
  nitter/lang/de/messages.po
  nitter/lang/de/strings.php
Labels: 2021.12, Hackathon 2021

#1173 [twitter] Add unfollow hook function
  twitter/twitter.php
Labels: 2021.12

#1177 [twitter] Add support for the new support_follow hook
  twitter/twitter.php
Labels: 2021.12, Hackathon 2021

#1178 [twitter] Add support for block and unblock hooks
  twitter/twitter.php
Labels: 2021.12

#1179 [twitter] Comment out remote post deletion currently never triggered
  twitter/twitter.php
Labels: 2021.12, Hackathon 2021

#1180 Replacing "q" calls with "DBA" calls
  dwpost/dwpost.php
  gravatar/gravatar.php
  ijpost/ijpost.php
  ljpost/ljpost.php
  mailstream/mailstream.php
  pumpio/pumpio.php
  statusnet/statusnet.php
  widgets/widgets.php
  windowsphonepush/windowsphonepush.php
Labels: Hackathon 2021

#1181 [advancedcontentfilter] Remove event.adjust field from available fields to match
  advancedcontentfilter/advancedcontentfilter.php
  advancedcontentfilter/doc/advancedcontentfilter.md
Labels: 2021.12, Hackathon 2021

#1182 Moved widgets and remote permissions to the deprecated addons
  remote_permissions/README.md
  remote_permissions/lang/C/messages.po
  remote_permissions/lang/ca/strings.php
  remote_permissions/lang/cs/messages.po
  remote_permissions/lang/cs/strings.php
  remote_permissions/lang/de/messages.po
  remote_permissions/lang/de/strings.php
  remote_permissions/lang/eo/strings.php
  remote_permissions/lang/es/messages.po
  remote_permissions/lang/es/strings.php
  remote_permissions/lang/fi-fi/messages.po
  remote_permissions/lang/fi-fi/strings.php
  remote_permissions/lang/fr/strings.php
  remote_permissions/lang/hu/messages.po
  remote_permissions/lang/hu/strings.php
  remote_permissions/lang/is/strings.php
  remote_permissions/lang/it/messages.po
  remote_permissions/lang/it/strings.php
  remote_permissions/lang/nb-no/strings.php
  remote_permissions/lang/nl/messages.po
  remote_permissions/lang/nl/strings.php
  remote_permissions/lang/pl/messages.po
  remote_permissions/lang/pl/strings.php
  remote_permissions/lang/pt-br/strings.php
  remote_permissions/lang/ro/messages.po
  remote_permissions/lang/ro/strings.php
  remote_permissions/lang/ru/strings.php
  remote_permissions/lang/sv/strings.php
  remote_permissions/lang/zh-cn/strings.php
  remote_permissions/remote_permissions.php
  remote_permissions/settings.css
  remote_permissions/templates/admin.tpl
  remote_permissions/templates/settings.tpl
  widgets/lang/C/messages.po
  widgets/lang/ca/strings.php
  widgets/lang/cs/strings.php
  widgets/lang/de/strings.php
  widgets/lang/eo/strings.php
  widgets/lang/es/strings.php
  widgets/lang/fr/strings.php
  widgets/lang/is/strings.php
  widgets/lang/it/strings.php
  widgets/lang/nb-no/strings.php
  widgets/lang/pl/strings.php
  widgets/lang/pt-br/strings.php
  widgets/lang/ru/strings.php
  widgets/lang/sv/strings.php
  widgets/lang/zh-cn/strings.php
  widgets/templates/settings.tpl
  widgets/templates/widget_like.tpl
  widgets/widget_friendheader.php
  widgets/widget_friends.php
  widgets/widget_like.php
  widgets/widgets.js
  widgets/widgets.php
Labels: 2021.12

#1162 WebDav Storage backend
  webdav_storage/composer.json
  webdav_storage/lang/C/messages.po
  webdav_storage/src/WebDav.php
  webdav_storage/src/WebDavConfig.php
  webdav_storage/tests/WebDavTest.php.bak
  webdav_storage/webdav_storage.php
Labels: 2021.12
