Repository friendica/friendica-addons, pull requests merged in 2022-06, with the labels that each got.

#1256 RU translation updates
  ijpost/lang/ru/messages.po
  ijpost/lang/ru/strings.php
  planets/lang/ru/messages.po
  planets/lang/ru/strings.php
  startpage/lang/ru/messages.po
  startpage/lang/ru/strings.php
Labels: 2022.05

#1257 Update unicode_smilies.php
  unicode_smilies/unicode_smilies.php
Labels: 2022.06

#1259 mark the whindowsphonepush as unsupported
  windowsphonepush/windowsphonepush.php
Labels: 2022.09

#1266 [qcomment] Fix wrong type hint for footer hook function
  qcomment/qcomment.php
Labels: 2022.09

#1267 Use labels for woodpecker continuous deployments
  .woodpecker/.continuous-deployment.yml
  .woodpecker/.releaser.yml
Labels: 2022.09

#1268 [various] Fix hook function type-hints
  mathjax/mathjax.php
  pageheader/pageheader.php
  saml/saml.php
  showmore_dyn/showmore_dyn.php
Labels: 2022.09

#1269 Changed type-hints and changed double-quotes to single
  blackout/blackout.php
  blockbot/blockbot.php
  cookienotice/cookienotice.php
  curweather/curweather.php
  geocoordinates/geocoordinates.php
  gravatar/gravatar.php
  impressum/impressum.php
  irc/irc.php
  keycloakpassword/keycloakpassword.php
  libravatar/libravatar.php
  mailstream/mailstream.php
  mathjax/mathjax.php
  newmemberwidget/newmemberwidget.php
  nitter/nitter.php
  nominatim/nominatim.php
  notifyall/notifyall.php
  openstreetmap/openstreetmap.php
  pageheader/pageheader.php
  piwik/piwik.php
  public_server/public_server.php
  qcomment/qcomment.php
  rendertime/rendertime.php
  saml/saml.php
  showmore_dyn/showmore_dyn.php
  statusnet/statusnet.php
  tumblr/tumblr.php
  twitter/twitter.php
  viewsrc/viewsrc.php
  webrtc/webrtc.php
Labels: 2022.09
